name: workflow
on: [push]
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Prepare
        run: yarn ci
      - name: Lint
        run: yarn lint
      - name: Typecheck
        run: yarn typecheck
#      - name: Lint
#        uses: mooyoul/tslint-actions@v1.1.1
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          pattern: '*.ts'